# This file is used by the Thunderstore CLI to build and publish your mod to Thunderstore. https://github.com/thunderstore-io/thunderstore-cli

[config]
schemaVersion = "0.0.1"

[package]
namespace = "ResoniteModding"
name = "BepisModSettings"
versionNumber = "1.2.0"
description = "Lets you edit your mod settings in the settings tab of the dashboard"
websiteUrl = "https://github.com/ResoniteModding/BepisModSettings"
containsNsfwContent = false

[package.dependencies]
ResoniteModding-BepisLoader = "1.4.1"
ResoniteModding-BepisLocaleLoader = "1.1.0"
ResoniteModding-BepisResoniteWrapper = "1.0.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./BepisModSettings/bin/Release/BepisModSettings.dll"
target = "plugins/BepisModSettings/"

[[build.copy]]
source = "./BepisModSettings/bin/Release/BepisModSettings.pdb"
target = "plugins/BepisModSettings/"

[[build.copy]]
source = "./BepisModSettings/Locale"
target = "plugins/BepisModSettings/Locale"

[[build.copy]]
source = "./LICENSE"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["resonite"]

[publish.categories]
resonite = [
  "dashboard",
  "misc",
]